import type { Metadata } from "next";
// import { Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

// const manrope = Manrope({
//   variable: "--font-title",
//   subsets: ["latin"],
//   display: "swap",
//   weight: "400",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <div>
          <Header />
          <div className="min-h-base150">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
